<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Atas</title>
</head>
<body>
    <h1>Cadastro de Atas</h1>
    <form action="/Ata/gravar" method="POST" enctype="multipart/form-data">
        <label for="titulo"><b>Número da Ata:</b></label><br></br>
        <input type="text" id="titulo" name="titulo" size="50" maxlength="40" 
        placeholder="Número da Ata" autocomplete="off" required class="formulario"><br><br>

        <label for="data"><b>Data da Assembleia:</b></label><br></br>
        <input type="text" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" placeholder="DD/MM/AAAA"
        id="dataAta" name="dataAta" size="50" maxlength="40" placeholder="Data da Assembleia" 
        autocomplete="off" required class="formulario"><br><br>


        <label for="local"><b>Local da Assembleia:</b></label><br></br>
        <input type="text" id="local" name="local" size="50" maxlength="40" 
        placeholder="Local da Assembleia" autocomplete="off" required class="formulario"><br><br>

        <label for="arquivo"><b>Arquivo Ata:</b></label><br></br>
        <input type="file" id="arquivo" name="arquivo" required><br><br>

        <a><b>Cadastrar Ata</b></a><br>
        <input type="submit" value="Submit" size="20" maxlength="40">

    </form>
</body>
</html>
