<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Atas</title>
</head>
<body>
    <h1>Cadastro de Membros</h1>
    <form action="/CadastroMembros/gravar" method="POST" enctype="multipart/form-data">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" required><br><br>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br><br>

        <label for="endereco">Logradouro</label>
        <input type="text" id="logradouro" name="logradouro" required><br><br>

        <label for="endereco">Número</label>
        <input type="text" id="numero" name="numero" required><br><br>

        <label for="endereco">Complemento</label>
        <input type="text" id="logradouro" name="complemento" required><br><br>

        <label for="endereco">Bairro</label>
        <input type="text" id="logradouro" name="bairro" required><br><br>

        <label for="endereco">Cidade</label>
        <input type="text" id="cidade" name="cidade" required><br><br>

        <label for="endereco">Estado</label>
        <input type="text" id="estado" name="estado" required><br><br>

        <label for="endereco">CEP</label>
        <input type="text" id="cep" name="cep" required><br><br>

        <label for="dataNascimento">Data de Nascimento:</label>
        <input type="date" id="dataNascimento" name="dataNascimento" required><br><br>

        <label for="cpf">CPF:</label>
        <input type="text" id="cpf" name="cpf" required><br><br>

        <label for="rg">RG:</label>
        <input type="text" id="rg" name="rg" required><br><br>

        <label for="estadoCivil">Estado Civil:</label>
		<select name="estadoCivil" class="formulario" required>
			<option value="">Selecione uma opção</option>
			<option value="Casado">Casado</option>
			<option value="Solteiro">Solteiro</option>
			<option value="Divorciado">Divorciado</option>
            <option value="Viúvo">Viúvo</option>
            <option value="Não informado">Não informado</option>
		</select> <br><br>

        <label for="telefone">Telefone do Membro:</label>
        <input type="text" id="telefone" name="telefone" required><br><br>

        <input type="submit" value="Cadastrar Membro">
</body>
</html>