<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Atas</title>
</head>
<body>
    <h1>Cadastro de Membros</h1>
    <form action="/CadastroMembros/gravar" method="POST" enctype="multipart/form-data">
        <label for="nome"><b>Nome:</b></label><br>
        <input type="text" id="nome" name="nome" size="50" maxlength="40" 
        placeholder="Nome do Membro" autocomplete="off" required class="formulario"><br><br>

        <label for="email"><b>Email:</b></label><br>
        <input type="email" id="email" name="email" size="50" maxlength="40" 
        placeholder="Email do Membro" autocomplete="off" required class="formulario"><br><br>

        <label for="endereco"><b>Logradouro</b></label><br>
        <input type="text" id="logradouro" name="logradouro" size="50" maxlength="40" 
        placeholder="Digite o Nome da Rua" autocomplete="off" required class="formulario"><br><br>

        <label for="endereco"><b>Número</b></label><br>
        <input type="text" id="numero" name="numero" size="50" maxlength="40" 
        placeholder="Digite o Número do Endereço" autocomplete="off" required class="formulario"><br><br>

        <label for="endereco"><b>Complemento</b></label><br>
        <input type="text" id="logradouro" name="complemento" size="50" maxlength="40" 
        placeholder="Digite um Complemento" autocomplete="off" required class="formulario"><br><br>

        <label for="endereco"><b>Bairro</b></label><br>
        <input type="text" id="logradouro" name="bairro" size="50" maxlength="40" 
        placeholder="Digite o Nome do Bairro" autocomplete="off" required class="formulario"><br><br>

        <label for="endereco"><b>Cidade</b></label><br>
        <input type="text" id="cidade" name="cidade" size="50" maxlength="40" 
        placeholder="Digite o Nome da Cidade" autocomplete="off" required class="formulario"><br><br>

        <label for="endereco"><b>Estado</b></label><br>
        <input type="text" id="estado" name="estado" size="50" maxlength="40" 
        placeholder="Digite o Nome do Estado" autocomplete="off" required class="formulario"><br><br>

        <label for="endereco"><b>CEP</b></label><br>
        <input type="text" id="cep" name="cep" size="50" maxlength="40" 
        placeholder="Digite o CEP" autocomplete="off" required class="formulario"><br><br>

        <label for="dataNascimento"><b>Data de Nascimento:</b></label><br>
        <input type="text" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" placeholder="DD/MM/AAAA"
        id="dataNascimento" name="dataNascimento" required><br><br>

        <label for="cpf"><b>CPF:</b></label><br>
        <input type="text" id="cpf" name="cpf" size="50" maxlength="40" 
        placeholder="Digite o CPF" autocomplete="off" required class="formulario"><br><br>

        <label for="rg"><b>RG:</b></label><br>
        <input type="text" id="rg" name="rg"size="50" maxlength="40" 
        placeholder="Digite o RG" autocomplete="off" required class="formulario"><br><br>

        <label for="estadoCivil"><b>Estado Civil:<b></label><br>
		<select name="estadoCivil" class="formulario" required>
			<option value="">Selecione uma opção</option>
			<option value="Casado">Casado</option>
			<option value="Solteiro">Solteiro</option>
			<option value="Divorciado">Divorciado</option>
            <option value="Viúvo">Viúvo</option>
            <option value="Não informado">Não informado</option>
		</select> <br><br>

        <label for="telefone"><b>Telefone do Membro:<b></label><br>
        <input type="text" id="telefone" name="telefone" size="50" maxlength="40" 
        placeholder="Digite o Número de Contato" autocomplete="off" required class="formulario"><br><br>

        <input type="submit" value="Cadastrar Membro">
</body>
</html>