<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Atas</title>
</head>
<body>
    <h1>Lista de Atas</h3>
    <a href="listar_atas.php">Ver Atas Cadastradas</a> <br><br>
    <h1>Lista de Assinaturas</h3>
    <a href="listar_assinaturas.php">Ver Assinaturas Cadastradas</a>
</body>
</html>